### ISSUE TITLE
slet sidste minut i datapoints (fordi det indeholder ikke nødvendigvis nok punkter)

### ISSUE THREAD

**Issue by Lildhansen** [NikolajKrogh/P6#87]
hvis den allerede fjerner med det modulo stuff skal den ikke alligevel

**Comment by NikolajKrogh** [comment]
Kan godt være jeg ikke helt forstår det, men lige nu er vores TIME_WINDOW_LENGTH sat til at være 1. Så det vil sige så længe det er en int, hvilket et minut altid vil være så er $x mod 1$ vel altid $0$? Så den vil vel aldrig fjerne noget?
